{% set name = "rdkit-postgresql" %}
{% set version = "2022.09.5" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: 2efe7ce3b527df529ed3e355e2aaaf14623e51876be460fa4ad2b7f7ad54c9b1

build:
  number: 0
  #skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - jom  # [win]
  host:
    - boost-cpp
    - eigen
    - postgresql {{ postgresql }}
    - freetype
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('postgresql', max_pin='x.x') }}
    - freetype
