{% set name = "rdkit-postgresql" %}
{% set version = "2022.09.5" %}
{% set git_rev = "Release_2022_09_5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: {{ git_rev }}
  patches:
    - CMakeLists.txt.patch  # [win]

build:
  number: 0
  #skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - jom  # [win]
  host:
    - boost-cpp
    - eigen
    - postgresql {{ postgresql }}
    - freetype
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('postgresql', max_pin='x.x') }}
    - freetype
