name: conda-build
run-name: ${{ github.actor }} is running a conda build
on: [push]
jobs:
  package:
    name: package for ${{ matrix.config.platform }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            platform: linux-64
            shell: bash -el {0}
          - os: macos-latest
            platform: osx-64
            shell: bash -el {0}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Setup a miniforge distribution
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          show-channel-urls: true
          activate-environment: ""
      # Display some diagnostic info and configure the conda installation
      - name: Run conda info
        shell: ${{ matrix.config.shell}}
        run: |
          conda config --set always_yes yes
          conda install conda-build conda-verify anaconda-client
          conda config --set anaconda_upload yes
          conda info
